require 'cudnn'
local model = {}
-- warning: module 'data [type Data]' not found
table.insert(model, {'conv1/7x7_s2', cudnn.SpatialConvolution(3, 64, 7, 7, 2, 2, 3, 3, 1)})
table.insert(model, {'conv1/relu_7x7', cudnn.ReLU(true)})
table.insert(model, {'pool1/3x3_s2', cudnn.SpatialMaxPooling(3, 3, 2, 2, 0, 0):ceil()})
table.insert(model, {'pool1/norm1', cudnn.SpatialCrossMapLRN(5, 0.000100, 0.7500, 1.000000)})
table.insert(model, {'conv2/3x3_reduce', cudnn.SpatialConvolution(64, 64, 1, 1, 1, 1, 0, 0, 1)})
table.insert(model, {'conv2/relu_3x3_reduce', cudnn.ReLU(true)})
table.insert(model, {'conv2/3x3', cudnn.SpatialConvolution(64, 192, 3, 3, 1, 1, 1, 1, 1)})
table.insert(model, {'conv2/relu_3x3', cudnn.ReLU(true)})
table.insert(model, {'conv2/norm2', cudnn.SpatialCrossMapLRN(5, 0.000100, 0.7500, 1.000000)})
table.insert(model, {'pool2/3x3_s2', cudnn.SpatialMaxPooling(3, 3, 2, 2, 0, 0):ceil()})
-- warning: module 'pool2/3x3_s2_pool2/3x3_s2_0_split [type Split]' not found
table.insert(model, {'inception_3a/1x1', cudnn.SpatialConvolution(192, 64, 1, 1, 1, 1, 0, 0, 1)})
table.insert(model, {'inception_3a/relu_1x1', cudnn.ReLU(true)})
table.insert(model, {'inception_3a/3x3_reduce', cudnn.SpatialConvolution(192, 96, 1, 1, 1, 1, 0, 0, 1)})
table.insert(model, {'inception_3a/relu_3x3_reduce', cudnn.ReLU(true)})
table.insert(model, {'inception_3a/3x3', cudnn.SpatialConvolution(96, 128, 3, 3, 1, 1, 1, 1, 1)})
table.insert(model, {'inception_3a/relu_3x3', cudnn.ReLU(true)})
table.insert(model, {'inception_3a/5x5_reduce', cudnn.SpatialConvolution(192, 16, 1, 1, 1, 1, 0, 0, 1)})
table.insert(model, {'inception_3a/relu_5x5_reduce', cudnn.ReLU(true)})
table.insert(model, {'inception_3a/5x5', cudnn.SpatialConvolution(16, 32, 5, 5, 1, 1, 2, 2, 1)})
table.insert(model, {'inception_3a/relu_5x5', cudnn.ReLU(true)})
table.insert(model, {'inception_3a/pool', cudnn.SpatialMaxPooling(3, 3, 1, 1, 1, 1):ceil()})
table.insert(model, {'inception_3a/pool_proj', cudnn.SpatialConvolution(192, 32, 1, 1, 1, 1, 0, 0, 1)})
table.insert(model, {'inception_3a/relu_pool_proj', cudnn.ReLU(true)})
-- warning: module 'inception_3a/output [type Concat]' not found
-- warning: module 'inception_3a/output_inception_3a/output_0_split [type Split]' not found
table.insert(model, {'inception_3b/1x1', cudnn.SpatialConvolution(256, 128, 1, 1, 1, 1, 0, 0, 1)})
table.insert(model, {'inception_3b/relu_1x1', cudnn.ReLU(true)})
table.insert(model, {'inception_3b/3x3_reduce', cudnn.SpatialConvolution(256, 128, 1, 1, 1, 1, 0, 0, 1)})
table.insert(model, {'inception_3b/relu_3x3_reduce', cudnn.ReLU(true)})
table.insert(model, {'inception_3b/3x3', cudnn.SpatialConvolution(128, 192, 3, 3, 1, 1, 1, 1, 1)})
table.insert(model, {'inception_3b/relu_3x3', cudnn.ReLU(true)})
table.insert(model, {'inception_3b/5x5_reduce', cudnn.SpatialConvolution(256, 32, 1, 1, 1, 1, 0, 0, 1)})
table.insert(model, {'inception_3b/relu_5x5_reduce', cudnn.ReLU(true)})
table.insert(model, {'inception_3b/5x5', cudnn.SpatialConvolution(32, 96, 5, 5, 1, 1, 2, 2, 1)})
table.insert(model, {'inception_3b/relu_5x5', cudnn.ReLU(true)})
table.insert(model, {'inception_3b/pool', cudnn.SpatialMaxPooling(3, 3, 1, 1, 1, 1):ceil()})
table.insert(model, {'inception_3b/pool_proj', cudnn.SpatialConvolution(256, 64, 1, 1, 1, 1, 0, 0, 1)})
table.insert(model, {'inception_3b/relu_pool_proj', cudnn.ReLU(true)})
-- warning: module 'inception_3b/output [type Concat]' not found
table.insert(model, {'pool3/3x3_s2', cudnn.SpatialMaxPooling(3, 3, 2, 2, 0, 0):ceil()})
-- warning: module 'pool3/3x3_s2_pool3/3x3_s2_0_split [type Split]' not found
table.insert(model, {'inception_4a/1x1', cudnn.SpatialConvolution(480, 192, 1, 1, 1, 1, 0, 0, 1)})
table.insert(model, {'inception_4a/relu_1x1', cudnn.ReLU(true)})
table.insert(model, {'inception_4a/3x3_reduce', cudnn.SpatialConvolution(480, 96, 1, 1, 1, 1, 0, 0, 1)})
table.insert(model, {'inception_4a/relu_3x3_reduce', cudnn.ReLU(true)})
table.insert(model, {'inception_4a/3x3', cudnn.SpatialConvolution(96, 208, 3, 3, 1, 1, 1, 1, 1)})
table.insert(model, {'inception_4a/relu_3x3', cudnn.ReLU(true)})
table.insert(model, {'inception_4a/5x5_reduce', cudnn.SpatialConvolution(480, 16, 1, 1, 1, 1, 0, 0, 1)})
table.insert(model, {'inception_4a/relu_5x5_reduce', cudnn.ReLU(true)})
table.insert(model, {'inception_4a/5x5', cudnn.SpatialConvolution(16, 48, 5, 5, 1, 1, 2, 2, 1)})
table.insert(model, {'inception_4a/relu_5x5', cudnn.ReLU(true)})
table.insert(model, {'inception_4a/pool', cudnn.SpatialMaxPooling(3, 3, 1, 1, 1, 1):ceil()})
table.insert(model, {'inception_4a/pool_proj', cudnn.SpatialConvolution(480, 64, 1, 1, 1, 1, 0, 0, 1)})
table.insert(model, {'inception_4a/relu_pool_proj', cudnn.ReLU(true)})
-- warning: module 'inception_4a/output [type Concat]' not found
-- warning: module 'inception_4a/output_inception_4a/output_0_split [type Split]' not found
table.insert(model, {'inception_4b/1x1', cudnn.SpatialConvolution(512, 160, 1, 1, 1, 1, 0, 0, 1)})
table.insert(model, {'inception_4b/relu_1x1', cudnn.ReLU(true)})
table.insert(model, {'inception_4b/3x3_reduce', cudnn.SpatialConvolution(512, 112, 1, 1, 1, 1, 0, 0, 1)})
table.insert(model, {'inception_4b/relu_3x3_reduce', cudnn.ReLU(true)})
table.insert(model, {'inception_4b/3x3', cudnn.SpatialConvolution(112, 224, 3, 3, 1, 1, 1, 1, 1)})
table.insert(model, {'inception_4b/relu_3x3', cudnn.ReLU(true)})
table.insert(model, {'inception_4b/5x5_reduce', cudnn.SpatialConvolution(512, 24, 1, 1, 1, 1, 0, 0, 1)})
table.insert(model, {'inception_4b/relu_5x5_reduce', cudnn.ReLU(true)})
table.insert(model, {'inception_4b/5x5', cudnn.SpatialConvolution(24, 64, 5, 5, 1, 1, 2, 2, 1)})
table.insert(model, {'inception_4b/relu_5x5', cudnn.ReLU(true)})
table.insert(model, {'inception_4b/pool', cudnn.SpatialMaxPooling(3, 3, 1, 1, 1, 1):ceil()})
table.insert(model, {'inception_4b/pool_proj', cudnn.SpatialConvolution(512, 64, 1, 1, 1, 1, 0, 0, 1)})
table.insert(model, {'inception_4b/relu_pool_proj', cudnn.ReLU(true)})
-- warning: module 'inception_4b/output [type Concat]' not found
-- warning: module 'inception_4b/output_inception_4b/output_0_split [type Split]' not found
table.insert(model, {'inception_4c/1x1', cudnn.SpatialConvolution(512, 128, 1, 1, 1, 1, 0, 0, 1)})
table.insert(model, {'inception_4c/relu_1x1', cudnn.ReLU(true)})
table.insert(model, {'inception_4c/3x3_reduce', cudnn.SpatialConvolution(512, 128, 1, 1, 1, 1, 0, 0, 1)})
table.insert(model, {'inception_4c/relu_3x3_reduce', cudnn.ReLU(true)})
table.insert(model, {'inception_4c/3x3', cudnn.SpatialConvolution(128, 256, 3, 3, 1, 1, 1, 1, 1)})
table.insert(model, {'inception_4c/relu_3x3', cudnn.ReLU(true)})
table.insert(model, {'inception_4c/5x5_reduce', cudnn.SpatialConvolution(512, 24, 1, 1, 1, 1, 0, 0, 1)})
table.insert(model, {'inception_4c/relu_5x5_reduce', cudnn.ReLU(true)})
table.insert(model, {'inception_4c/5x5', cudnn.SpatialConvolution(24, 64, 5, 5, 1, 1, 2, 2, 1)})
table.insert(model, {'inception_4c/relu_5x5', cudnn.ReLU(true)})
table.insert(model, {'inception_4c/pool', cudnn.SpatialMaxPooling(3, 3, 1, 1, 1, 1):ceil()})
table.insert(model, {'inception_4c/pool_proj', cudnn.SpatialConvolution(512, 64, 1, 1, 1, 1, 0, 0, 1)})
table.insert(model, {'inception_4c/relu_pool_proj', cudnn.ReLU(true)})
-- warning: module 'inception_4c/output [type Concat]' not found
-- warning: module 'inception_4c/output_inception_4c/output_0_split [type Split]' not found
table.insert(model, {'inception_4d/1x1', cudnn.SpatialConvolution(512, 112, 1, 1, 1, 1, 0, 0, 1)})
table.insert(model, {'inception_4d/relu_1x1', cudnn.ReLU(true)})
table.insert(model, {'inception_4d/3x3_reduce', cudnn.SpatialConvolution(512, 144, 1, 1, 1, 1, 0, 0, 1)})
table.insert(model, {'inception_4d/relu_3x3_reduce', cudnn.ReLU(true)})
table.insert(model, {'inception_4d/3x3', cudnn.SpatialConvolution(144, 288, 3, 3, 1, 1, 1, 1, 1)})
table.insert(model, {'inception_4d/relu_3x3', cudnn.ReLU(true)})
table.insert(model, {'inception_4d/5x5_reduce', cudnn.SpatialConvolution(512, 32, 1, 1, 1, 1, 0, 0, 1)})
table.insert(model, {'inception_4d/relu_5x5_reduce', cudnn.ReLU(true)})
table.insert(model, {'inception_4d/5x5', cudnn.SpatialConvolution(32, 64, 5, 5, 1, 1, 2, 2, 1)})
table.insert(model, {'inception_4d/relu_5x5', cudnn.ReLU(true)})
table.insert(model, {'inception_4d/pool', cudnn.SpatialMaxPooling(3, 3, 1, 1, 1, 1):ceil()})
table.insert(model, {'inception_4d/pool_proj', cudnn.SpatialConvolution(512, 64, 1, 1, 1, 1, 0, 0, 1)})
table.insert(model, {'inception_4d/relu_pool_proj', cudnn.ReLU(true)})
-- warning: module 'inception_4d/output [type Concat]' not found
-- warning: module 'inception_4d/output_inception_4d/output_0_split [type Split]' not found
table.insert(model, {'inception_4e/1x1', cudnn.SpatialConvolution(528, 256, 1, 1, 1, 1, 0, 0, 1)})
table.insert(model, {'inception_4e/relu_1x1', cudnn.ReLU(true)})
table.insert(model, {'inception_4e/3x3_reduce', cudnn.SpatialConvolution(528, 160, 1, 1, 1, 1, 0, 0, 1)})
table.insert(model, {'inception_4e/relu_3x3_reduce', cudnn.ReLU(true)})
table.insert(model, {'inception_4e/3x3', cudnn.SpatialConvolution(160, 320, 3, 3, 1, 1, 1, 1, 1)})
table.insert(model, {'inception_4e/relu_3x3', cudnn.ReLU(true)})
table.insert(model, {'inception_4e/5x5_reduce', cudnn.SpatialConvolution(528, 32, 1, 1, 1, 1, 0, 0, 1)})
table.insert(model, {'inception_4e/relu_5x5_reduce', cudnn.ReLU(true)})
table.insert(model, {'inception_4e/5x5', cudnn.SpatialConvolution(32, 128, 5, 5, 1, 1, 2, 2, 1)})
table.insert(model, {'inception_4e/relu_5x5', cudnn.ReLU(true)})
table.insert(model, {'inception_4e/pool', cudnn.SpatialMaxPooling(3, 3, 1, 1, 1, 1):ceil()})
table.insert(model, {'inception_4e/pool_proj', cudnn.SpatialConvolution(528, 128, 1, 1, 1, 1, 0, 0, 1)})
table.insert(model, {'inception_4e/relu_pool_proj', cudnn.ReLU(true)})
-- warning: module 'inception_4e/output [type Concat]' not found
table.insert(model, {'CAM_conv', cudnn.SpatialConvolution(832, 1024, 3, 3, 1, 1, 1, 1, 2)})
table.insert(model, {'CAM_relu', cudnn.ReLU(true)})
table.insert(model, {'CAM_pool', cudnn.SpatialAveragePooling(14, 14, 14, 14, 0, 0):ceil()})
table.insert(model, {'CAM_fc', nn.Linear(1024, 1000)})
return model